### ISSUE TITLE
容器启动时fate-network网段随机，通过down、up -d重启容器后，旧任务无法删除、导出数据和访问详细内容

### ISSUE THREAD

**Issue by KAndHisC** [FederatedAI/KubeFATE#121]
通过docker-compose 启动容器，假设第一次启动时fate-network的网段为172.19.0.x。
中间因为运维需求，（例如发起任务因故障失败，需要关闭容器修改配置），通过docker-compose down 和docker-compose up -d 重启容器组。重启后fate-network的网段为172.30.0.x。

则重启后，fateboard删除上一次运行中的任务会出现错误：please start execute server：172.19.0.4:9380
fateboard上旧任务的详细信息页面等也有类似报错。

解决途径有两个，一个是FATE本身修改任务的管理方式，不按照任务记录里的地址找server，另一个是在KubeFATE种固定容器网段

```
networks:
  fate-network:
    ipam:
      config:
      - subnet: 172.30.0.0/16
```
