### ISSUE TITLE
k8s部署KubeFATE时pod python进入  CrashLoopBackOff状态，其中的client容器一直在重启。

### ISSUE THREAD

**Issue by haikongyu** [FederatedAI/KubeFATE#277]
**What deployment mode you are use?  **
2. Kuberentes.

**What KubeFATE and FATE version you are using?  **
KubeFATE v1.5.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **
 - OS: CentOS
 - Version 7.8

**Desktop (please complete the following information):**

**To Reproduce**
Clear how to reproduce your problem.

**What happen?**
Clear the unexpected response.

**Screenshots**

**Additional context**
k8s查看pod信息为
Warning  BackOff  4m3s (x543 over 123m)  kubelet  Back-off restarting failed container

**Comment by haikongyu** [comment]
## 部署过程
### 新建kubefate文件夹（以后执行kubefate命令需要在此文件夹下）下载kubefate并解压
```
cd ~
mkdir kubefate

cd kubefate && wget https://github.com/FederatedAI/KubeFATE/releases/download/v1.5.0/kubefate-k8s-v1.5.0.tar.gz

tar -zxvf kubefate-k8s-v1.5.0.tar.gz
```
### 安装RBAC(AB双方master主机执行)
```
kubectl apply -f ./rbac-config.yaml
```

### 安装kubefate(AB双方master主机执行)
```
sed -i "147s|8080|80|" kubefate.yaml
kubectl apply -f ./kubefate.yaml
```
### 创建命名空间(AB双方master主机执行)
A方 master

```
kubectl create namespace fate-10000
```

B方 master

````
kubectl create namespace fate-9999
````

### 检查pod状态(AB双方master主机执行)
```
kubectl get pod -n kube-fate
```

当所有pod状态均为runnging时执行下一步

### 配置cluster信息
A方 master

```
sed -i "s|registry: \"\"|registry: \"hub.c.163.com/federatedai\"|" cluster.yaml

```

B方 master
```
sed -i "s|registry: \"\"|registry: \"hub.c.163.com/federatedai\"|" cluster.yaml

```
### kubefate移入到服务(AB双方master主机执行)
````
chmod +x ./kubefate && sudo mv ./kubefate /usr/local/bin/kubefate
````
### 获取kubefate的cluster ip(双方分别执行)
```
kubectl get svc -n kube-fate
```

假设得到ip 为$ip, 执行

```
echo $ip kubefate.net >> /etc/hosts
```
### 修正mariadb
进入mariadb容器
```
kubectl exec -it svc/mariadb -n kube-fate -- bash
```
登录mysql
```
mysql -u kubefate -p
```
密码:kubefate


修正
```
use databases kube_fate;
ALTER TABLE helm_charts MODIFY templates mediumblob;
```
退出 mysql
```
exit
```
退出容器
```
ctrl + A +D
```
### 开始部署(AB双方master主机执行)
```
kubefate cluster install -f ./cluster.yaml
```

### 查看部署进度(AB双方master主机执行)
```
kubefate job ls
```

当状态为sucess时部署完成

## 测试toy_example
### 双方分别进入容器
A方 master

```bash
kubectl exec -it svc/fateflow -c python -n fate-10000 -- bash
```

B方 master

```bash
kubectl exec -it svc/fateflow -c python -n fate-9999 -- bash
```

### 开始测试
A方master执行
```
cd examples/toy_example/
python run_toy_example.py 10000 9999 1

**Comment by haikongyu** [comment]
通过查错找到以下
[root@k8s-master1 kubefate]# kubectl logs  python-88764749b-9qrbg  -c client -n fate-10000
Usage: flow init [OPTIONS]
Try 'flow init -h' for help.

Error: Invalid value for '-c' / '--server-conf-path': Path '/data/projects/fate/conf/service_conf.yaml' does not exist.

**Comment by haikongyu** [comment]
应该是client:1.5.0-release容器有问题

**Comment by haikongyu** [comment]
问题查明，确系bug，当前版本可通过修改deployment/python进行更正
```
# 进入deployment/python开始修正
kubectl edit deployment python -n fate-10000
```
修正前
```
        image: hub.c.163.com/federatedai/client:1.5.0-release
        imagePullPolicy: IfNotPresent
        name: client
        ports:
        - containerPort: 20000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
```
修正后
```
        image: hub.c.163.com/federatedai/client:1.5.0-release
        imagePullPolicy: IfNotPresent
        name: client
        command: ["/bin/bash"]
        args: ["-c", "flow init --ip=${POD_IP} --port=9380 && pipeline init --ip=${POD_IP} --port=9380 && jupyter notebook --ip=0.0.0.0 --port=20000 --allow-root --debug --NotebookApp.notebook_dir='/fml_manager/Examples' --no-browser --NotebookApp.token='' --NotebookApp.password=''"]
        ports:
        - containerPort: 20000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
```
bug出现原因：federatedai/client容器dockerfile 内CMD命令使用了不存在的文件，需使用k8s覆盖其CMD命令
