### ISSUE TITLE
Problem with create two cluster with same party_id

### ISSUE THREAD

**Issue by asdfsx** [FederatedAI/KubeFATE#376]
**What deployment mode you are use?**
minikube

**What KubeFATE and FATE version you are using?**
kubefate 1.5.0

**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.**
mac

**To Reproduce**

I create 2 namespace fate-9999, fate-10000. 

Then I tried to install fate cluster into these 2 namespace, with same party_id 9999.

**What happen?**
The 1st cluster create successfully, but the 2nd failed cause: 
```
2021-03-15T03:18:59Z ERR workspace/pkg/modules/cluster_helm.go:63 > values yaml Unmarshal error error="admission webhook \"validate.nginx.ingress.kubernetes.io\" denied the request: host \"9999.fateboard.kubefate.net\" and path \"/\" is already defined in ingress fate-9999/fateboard"
2021-03-15T03:18:59Z ERR workspace/pkg/job/job.go:96 > helm install cluster error error="admission webhook \"validate.nginx.ingress.kubernetes.io\" denied the request: host \"9999.fateboard.kubefate.net\" and path \"/\" is already defined in ingress fate-9999/fateboard" ClusterId=f58cc255-8dbb-4a31-a5bb-3e4075c18f33
```

**Screenshots**
![image](https://user-images.githubusercontent.com/2292716/111100453-c575b380-8582-11eb-9b5a-a9ef68817f69.png)

error logs
![image](https://user-images.githubusercontent.com/2292716/111100517-e6d69f80-8582-11eb-8f54-12b332c08654.png)

**Additional context**

I don't know whether kubefate is supporting create 2 cluster with same party_id. 

If not, party_id can be checked before sent it to helm client.

@jiahaoc1993

**Comment by asdfsx** [comment]
It seems 1.5.1 resolve ingress problem by adding customized host config into helm chart. 

```
{{- with .host }}
host:
  fateboard: {{ .fateboard | default (printf "%v.fateboard.kubefate.net" $partyId) }}
  client: {{ .client | default (printf "%v.notebook.kubefate.net" $partyId) }}
  sparkUI: {{ .sparkUI | default (printf "%v.spark.kubefate.net" $partyId) }}
  rabbitmqUI: {{ .rabbitmqUI | default (printf "%v.rabbitmq.kubefate.net" $partyId) }}
{{- else }}
host:
  fateboard: {{ .partyId }}.fateboard.kubefate.net
  client: {{ .partyId }}.notebook.kubefate.net
  sparkUI: {{ .partyId }}.spark.kubefate.net
  rabbitmqUI: {{ .partyId }}.rabbitmq.kubefate.net
{{- end }}
```

so now I can create two cluster with same party_id, but one of them should add specific host config.
