### ISSUE TITLE
Fate On Spark集群，部署后，双边测试报错（原生集群与k8s安装后报错一致）

### ISSUE THREAD

**Issue by stevenqyx** [FederatedAI/KubeFATE#568]
**您好，我在部署Fate On Spark集群时，部署后，双边测试报错。报错信息如下：**
```
 stdout:{
     "data": {
         "guest": {
             "9999": {
                 "retcode": 0,
                 "retmsg": "success"
             }
         },
         "host": {
             "10000": {
                 "retcode": 104,
                 "retmsg": "Federated schedule error, remote http request error: Expecting value: line 1 column 1 (char 0)"
             }
         }
     },
     "retcode": 100,
     "retmsg": "create job failed"
 }
```
组件版本，与文档一致
1.	miniKube: v1.7.3
2.     kubectl: v1.17.3
3.     kubefate:v1.6.0
4.     fate:v1.6.0
**其中cluster-spark.yaml配置如下：**
```
 name: fate-10000
 namespace: fate-10000
 chartName: fate
 chartVersion: v1.6.0
 partyId: 10000
 registry: ""
 imageTag: ""
 pullPolicy: 
 persistence: false
 istio:
   enabled: false
 modules:
   # - rollsite
   # - clustermanager
   # - nodemanager
   - mysql
   - python
   - fateboard
   # - client
   - spark
   - hdfs
   - nginx
   - rabbitmq
 
 backend: spark
 
 # rollsite: 
   # type: NodePort
   # nodePort: 30091
   # exchange:
     # ip: 192.168.0.1
     # port: 30000
   # partyList:
   # - partyId: 10000
     # partyIp: 192.168.0.1
     # partyPort: 30101
   # nodeSelector: 
 
 # nodemanager:
   # count: 3
   # sessionProcessorsPerNode: 4
   # storageClass: "nodemanagers"
   # accessMode: ReadWriteOnce
   # size: 2Gi
   # list:
   # - name: nodemanager
     # nodeSelector: 
     # sessionProcessorsPerNode: 4
     # subPath: "nodemanager"
     # existingClaim: ""
     # storageClass: "nodemanager"
     # accessMode: ReadWriteOnce
     # size: 1Gi
 
 python:
   type: NodePort
   nodePort: 30102
   nodeSelector: 
   spark: 
     master: spark://spark-master:7077
     home: 
     cores_per_node: 20
     nodes: 2
   hdfs:
     name_node: hdfs://namenode:9000
     path_prefix:
   rabbitmq:
     host: rabbitmq
     mng_port: 15672
     port: 5672
     user: fate
     password: fate
     # default conf/rabbitmq_route_table.yaml
     route_table: 
   nginx:
     host: nginx
     http_port: 9300
     grpc_port: 9310
 mysql: 
   nodeSelector: 
   ip: mysql
   port: 3306
   database: eggroll_meta
   user: fate
   password: fate_dev
   subPath: ""
   existingClaim: ""
   storageClass: "mysql"
   accessMode: ReadWriteOnce
   size: 1Gi
 
 # #
 # #externalMysqlIp: mysql
 # #externalMysqlPort: 3306
 # #externalMysqlDatabase: eggroll_meta
 # #externalMysqlUser: fate
 # #externalMysqlPassword: fate_dev
 
 
 # servingIp: 192.168.0.1
 # servingPort: 30095
 
 ## cluster of FATE on spark configuration
 
 spark:
   master:
     Image: "federatedai/spark-master"
     ImageTag: "1.5.0-release"
     replicas: 1
     cpu: "100m"
     memory: "512Mi"
     nodeSelector: 
     type: ClusterIP
   worker:
     Image: "federatedai/spark-worker"
     ImageTag: "1.5.0-release"
     replicas: 2
     cpu: "1000m"
     memory: "512Mi"
     nodeSelector: 
     type: ClusterIP
 hdfs:
   namenode:
     nodeSelector: 
     type: ClusterIP
   datanode:
     nodeSelector: 
     type: ClusterIP
 nginx:
   nodeSelector: 
   type: ClusterIP
   httpNodePort: 30093
   grpcNodePort: 30098
   route_table: 
     9999: 
       proxy: 
         - host: 192.168.118.103 
           http_port: 30103
           grpc_port: 30108 
       fateflow: 
         - host: 192.168.118.103
           http_port: 30107
           grpc_port: 30102
 rabbitmq:
   nodeSelector: 
   type: ClusterIP
   nodePort: 30094
   default_user: fate
   default_pass: fate
   user: fate
   password: fate
   route_table:
     9999:
       host: 192.168.118.103
       port: 30104
```
