### ISSUE TITLE
Fate 1.5.0 Docker- compose部署，upload失败

### ISSUE THREAD

**Issue by FranisiL** [FederatedAI/KubeFATE#579]
**What deployment mode you are use?  **
    1. docker-compose;

**What KubeFATE and FATE version you are using?  **

**MUST** Please state the KubeFATE and FATE version you found the issue
    1. Fate 1.5.0
**What OS you are using for docker-compse or Kubernetes? Please also clear the version of OS.  **

    1. CentOS Linux release 7.9.2009
    2. 16core
    3. 1T

**Desktop (please complete the following information):**

**To Reproduce**

1. [部署文档](https://github.com/FederatedAI/KubeFATE/blob/v1.5.0/docker-deploy/README_zh.md)
2. 在容器内部上传一个500列特征、10w数据量的一个数据集，文件大小300M左右
3. 执行上传命令 _python ./fate_flow_client.py  -f upload -c ./upload_idCard.json -drop 1_
4. upload_idCard.json内容如下
`{
    "file": "/external_share/file/1648624306059",
    "head": 1,
    "partition": 16,
    "work_mode": 1,
    "backend": 1,
    "storage_engine": "HDFS",
    "use_local_data": 0,
    "table_name": "1648624306059",
    "namespace": "expro"
}`

**What happen?**
[ERROR] [2022-03-30 11:42:54,088] [1019:140409311278912] - task_executor.py[line:196]: HDFS CloseFile failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
Traceback (most recent call last):
  File "./fate/python/fate_arch/storage/hdfs/_table.py", line 86, in put_all
    writer.write(hdfs_utils.serialize(k, v))
  File "pyarrow/io.pxi", line 284, in pyarrow.lib.NativeFile.write
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: HDFS Write failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./fate/python/fate_flow/operation/task_executor.py", line 174, in run_task
    run_object.run(component_parameters_on_party, task_run_args)
  File "./fate/python/fate_flow/components/upload.py", line 100, in run
    data_table_count = self.save_data_table(job_id, name, namespace, head)
  File "./fate/python/fate_flow/components/upload.py", line 135, in save_data_table
    self.table.put_all(data)
  File "./fate/python/fate_arch/storage/hdfs/_table.py", line 88, in put_all
    counter = counter + 1
  File "pyarrow/io.pxi", line 133, in pyarrow.lib.NativeFile.close
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
OSError: HDFS CloseFile failed, errno: 255 (Unknown error 255) Please check that you are connecting to the correct HDFS RPC port
36
[INFO] [2022-03-30 11:42:54,090] [1019:140409311278912] - task_executor.py[line:302]: report task 202203301142467390905_upload_0 0 local 0 to driver

**Comment by owlet42** [comment]
Please use a newer version such as 1.7.2 or 1.5.3

**Comment by FranisiL** [comment]
@owlet42 Thank you for your reply. I redeployed fate version 1.7.2 according to your requirements, but the problem still exists. At least after deploying with kubefate's existing docker compose deployment document, the problem exists. The error message is like the communication problem between the namenode and datanode of Hadoop. The specific reason needs to be seen again.

**Comment by FranisiL** [comment]
方便贴一下报错信息吗 @JingChen23

**Comment by LaynePeng** [comment]
Can it be successful when the file to upload less than 100MB?

**Comment by stone-wlg** [comment]
i have the same issue before, you could try to scale datanode pod to 3. hope useful to you

**Comment by JingChen23** [comment]
Thanks @stone-wlg for the advice. We have verified that your solution is correct.

So for the docker-compose mode, the work around is:
In the file `docker-deploy/training_template/docker-compose-spark.yml`, currently there is only 1 data node:
```
  datanode:
    image: federatedai/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    restart: always
    volumes:
      - ./shared_dir/data/datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    env_file:
      - ./confs/hadoop/hadoop.env
    networks:
      - fate-network
```
We need to change it to 3, such as
```
  datanode-0:
    image: federatedai/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    restart: always
    volumes:
      - ./shared_dir/data/datanode-0:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    env_file:
      - ./confs/hadoop/hadoop.env
    networks:
      - fate-network
  datanode-1:
    image: federatedai/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    restart: always
    volumes:
      - ./shared_dir/data/datanode-1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    env_file:
      - ./confs/hadoop/hadoop.env
    networks:
      - fate-network
  datanode-2:
    image: federatedai/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    restart: always
    volumes:
      - ./shared_dir/data/datanode-2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9000"
    env_file:
      - ./confs/hadoop/hadoop.env
    networks:
      - fate-network
```
