### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by fuxingbit** [FederatedAI/KubeFATE#745]
# ./bin/kubefate cluster install -f ./cluster.yaml
invalid character '<' looking for beginning of value

使用最新master分支代码，编译kubefate使用go 1.18版本，k8s版本1.24.0，ingress-nginx：1.1.3版本

**Comment by JingChen23** [comment]
Can you post the cluster.yaml files' content here?

**Comment by fuxingbit** [comment]
默认文件，没有做任何修改
# cat cluster.yaml 
name: fate-9999
namespace: fate-9999
chartName: fate
chartVersion: v1.9.0
partyId: 9999
registry: ""
pullPolicy:
imagePullSecrets: 
- name: myregistrykey
persistence: false
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
ingressClassName: nginx
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - fateboard
  - client
  
# Computing : Eggroll, Spark, Spark_local
computing: Eggroll
# Federation: Eggroll(computing: Eggroll), Pulsar/RabbitMQ(computing: Spark/Spark_local)
federation: Eggroll
# Storage: Eggroll(computing: Eggroll), HDFS(computing: Spark), LocalFS(computing: Spark_local)
storage: Eggroll
# Algorithm: Basic, NN
algorithm: Basic
# Device: CPU, IPCL
device: CPU

# you can customize some keys which will be ignored in yaml validation
skippedKeys:
  - route_table

# Specify domain name for service
# ingress:
  # fateboard: 
    # hosts:
    # - name: party9999.fateboard.example.com
  # client:  
    # hosts:
    # - name: party9999.notebook.example.com
  # spark:  
    # hosts:
    # - name: party9999.spark.example.com
  # rabbitmq:  
    # hosts:
    # - name: party9999.rabbitmq.example.com
  # pulsar:  
    # hosts:
    # - name: party9999.pulsar.example.com
  
# Specify rollsite properties
# rollsite:
  # type: NodePort
  # nodePort: 30091
  # loadBalancerIP:
  # exchange:
    # ip: 192.168.0.1
    # port: 30000
  # partyList:
  # - partyId: 10000
    # partyIp: 192.168.0.1
    # partyPort: 30101
  # nodeSelector:
  # tolerations:
  # affinity:
  # polling:
    # enabled: true
    # type: server
    # # server:
      # # ip: 192.168.100.1
      # # port: 9370
    # clientList:
    # - partID: 9999
    # concurrency: 49
  # resources:
    # requests:
      # cpu: "1"
      # memory: "1Gi"
    # limits:
      # cpu: "4"
      # memory: "1Gi"

# Specify clustermanager properties
# clustermanager:
#   nodeSelector:
#   tolerations:
#   affinity:
  # resources:
    # requests:
      # cpu: "1"
      # memory: "1Gi"
    # limits:
      # cpu: "1"
      # memory: "1Gi"

# Specify nodemanager properties
# nodemanager:
#   replicas: 2
#   sessionProcessorsPerNode: 4
#   nodeSelector:
#   tolerations:
#   affinity:
#   subPath: "nodemanager"
#   storageClass: "local-scsi"
#   accessMode: ReadWriteOnce
#   size: 1Gi
  # resources:
    # requests:
      # cpu: "2"
      # memory: "4Gi"
    # limits:
      # cpu: "4"
      # memory: "8Gi"

# Specify the fateflow service's properties
# python:
  # type: NodePort
  # httpNodePort: 30097
  # grpcNodePort: 30092
  # loadBalancerIP:
  # serviceAccountName: ""
  # nodeSelector:
  # tolerations:
  # affinity:
  # enabledNN: false
  # logLevel: INFO
  # existingClaim: ""
  # storageClass: "python"
  # accessMode: ReadWriteMany
  # size: 1Gi
  # resources:
    # requests:
      # cpu: "2"
      # memory: "4Gi"
    # limits:
      # cpu: "4"
      # memory: "8Gi"
  # clustermanager:
    # cores_per_node: 16
    # nodes: 2

 # Specify the fateboard service's properties
# fateboard: 
  # type: ClusterIP
  # username: admin
  # password: admin

 # Specify the client service's properties
# client:
  # nodeSelector: 
  # subPath: ""
  # existingClaim: ""
  # storageClass: "client"
  # accessMode: ReadWriteOnce
  # size: 1Gi

# Specify the mysql properties
# mysql: 
  # nodeSelector:
  # tolerations:
  # affinity:
  # ip: mysql
  # port: 3306
  # database: eggroll_meta
  # user: fate
  # password: fate_dev
  # subPath: ""
  # existingClaim: ""
  # storageClass: "mysql"
  # accessMode: ReadWriteOnce
  # size: 1Gi

# #
# #externalMysqlIp: mysql
# #externalMysqlPort: 3306
# #externalMysqlDatabase: eggroll_meta
# #externalMysqlUser: fate
# #externalMysqlPassword: fate_dev

# Specify serving configuration
# servingIp: 192.168.0.1
# servingPort: 30095

**Comment by fuxingbit** [comment]
```
# cat cluster.yaml 
name: fate-9999
namespace: fate-9999
chartName: fate
chartVersion: v1.9.0
partyId: 9999
registry: ""
pullPolicy:
imagePullSecrets: 
- name: myregistrykey
persistence: false
istio:
  enabled: false
podSecurityPolicy:
  enabled: false
ingressClassName: nginx
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - fateboard
  - client
  
# Computing : Eggroll, Spark, Spark_local
computing: Eggroll
# Federation: Eggroll(computing: Eggroll), Pulsar/RabbitMQ(computing: Spark/Spark_local)
federation: Eggroll
# Storage: Eggroll(computing: Eggroll), HDFS(computing: Spark), LocalFS(computing: Spark_local)
storage: Eggroll
# Algorithm: Basic, NN
algorithm: Basic
# Device: CPU, IPCL
device: CPU

# you can customize some keys which will be ignored in yaml validation
skippedKeys:
  - route_table

# Specify domain name for service
# ingress:
  # fateboard: 
    # hosts:
    # - name: party9999.fateboard.example.com
  # client:  
    # hosts:
    # - name: party9999.notebook.example.com
  # spark:  
    # hosts:
    # - name: party9999.spark.example.com
  # rabbitmq:  
    # hosts:
    # - name: party9999.rabbitmq.example.com
  # pulsar:  
    # hosts:
    # - name: party9999.pulsar.example.com
  
# Specify rollsite properties
# rollsite:
  # type: NodePort
  # nodePort: 30091
  # loadBalancerIP:
  # exchange:
    # ip: 192.168.0.1
    # port: 30000
  # partyList:
  # - partyId: 10000
    # partyIp: 192.168.0.1
    # partyPort: 30101
  # nodeSelector:
  # tolerations:
  # affinity:
  # polling:
    # enabled: true
    # type: server
    # # server:
      # # ip: 192.168.100.1
      # # port: 9370
    # clientList:
    # - partID: 9999
    # concurrency: 49
  # resources:
    # requests:
      # cpu: "1"
      # memory: "1Gi"
    # limits:
      # cpu: "4"
      # memory: "1Gi"

# Specify clustermanager properties
# clustermanager:
#   nodeSelector:
#   tolerations:
#   affinity:
  # resources:
    # requests:
      # cpu: "1"
      # memory: "1Gi"
    # limits:
      # cpu: "1"
      # memory: "1Gi"

# Specify nodemanager properties
# nodemanager:
#   replicas: 2
#   sessionProcessorsPerNode: 4
#   nodeSelector:
#   tolerations:
#   affinity:
#   subPath: "nodemanager"
#   storageClass: "local-scsi"
#   accessMode: ReadWriteOnce
#   size: 1Gi
  # resources:
    # requests:
      # cpu: "2"
      # memory: "4Gi"
    # limits:
      # cpu: "4"
      # memory: "8Gi"

# Specify the fateflow service's properties
# python:
  # type: NodePort
  # httpNodePort: 30097
  # grpcNodePort: 30092
  # loadBalancerIP:
  # serviceAccountName: ""
  # nodeSelector:
  # tolerations:
  # affinity:
  # enabledNN: false
  # logLevel: INFO
  # existingClaim: ""
  # storageClass: "python"
  # accessMode: ReadWriteMany
  # size: 1Gi
  # resources:
    # requests:
      # cpu: "2"
      # memory: "4Gi"
    # limits:
      # cpu: "4"
      # memory: "8Gi"
  # clustermanager:
    # cores_per_node: 16
    # nodes: 2

 # Specify the fateboard service's properties
# fateboard: 
  # type: ClusterIP
  # username: admin
  # password: admin

 # Specify the client service's properties
# client:
  # nodeSelector: 
  # subPath: ""
  # existingClaim: ""
  # storageClass: "client"
  # accessMode: ReadWriteOnce
  # size: 1Gi

# Specify the mysql properties
# mysql: 
  # nodeSelector:
  # tolerations:
  # affinity:
  # ip: mysql
  # port: 3306
  # database: eggroll_meta
  # user: fate
  # password: fate_dev
  # subPath: ""
  # existingClaim: ""
  # storageClass: "mysql"
  # accessMode: ReadWriteOnce
  # size: 1Gi

# #
# #externalMysqlIp: mysql
# #externalMysqlPort: 3306
# #externalMysqlDatabase: eggroll_meta
# #externalMysqlUser: fate
# #externalMysqlPassword: fate_dev

# Specify serving configuration
# servingIp: 192.168.0.1
# servingPort: 30095
```
