### ISSUE TITLE
How to dynamically expand multiple parties

### ISSUE THREAD

**Issue by KAgBMan** [FederatedAI/KubeFATE#823]
Now I use the K8S to successfully deploy two parties, but now I need to add a participant for third-party computing, How can I add a participant without changing the status quo? Or can I only reinstall all clusters? Is there a place that can be configured to add the host and partyid of the third party?

**Comment by owlet42** [comment]
You can add new party information by modifying the `partyList` or `route_table` of cluster.yaml, and then use `kubefate cluster update -f cluster.yaml` to update the newly added party information to the existing cluster.

example:
```yaml

rollsite:
  type: NodePort
  nodePort: 30091
  partyList:
  - partyId: 9999
    partyIp: 192.168.9.1
    partyPort: 30091
  - partyId: 10000
    partyIp: 192.168.10.1
    partyPort: 30101
  - partyId: 8888
    partyIp: 192.168.8.1
    partyPort: 30081

```
