### ISSUE TITLE
Spark集群使用eggroll进行通信

### ISSUE THREAD

**Issue by FFinchR** [FederatedAI/KubeFATE#876]
https://github.com/FederatedAI/FATE/issues/4651
使用KubeFATE部署的集群，想要实现异构计算后端（Spark与Eggroll）的互联，使用eggroll进行通信
```yaml
computing: Spark
federation: Eggroll
storage: HDFS
algorithm: Basic
device: CPU
```
需要添加哪些module？
```yaml
modules:
  - mysql
  - python
  - fateboard
  - client
  - rollsite
  - clustermanager
  - nodemanager
  - spark
  - hdfs
```
