### ISSUE TITLE
upgrade doc is out-of-date

### ISSUE THREAD

**Issue by wood-j** [FederatedAI/KubeFATE#880]
**Is your feature request related to a problem? Please describe.**
No.
The version upgrade doc is out of date and may not working properly.

**Describe the solution you'd like**

I am tring to use [doc](https://github.com/FederatedAI/KubeFATE/blob/master/docs/FATE_Upgrade.md) to upgrade my cluster from `1.8.0` to `1.9.2` with all persistent data.

But as the `cluster.yaml` of 1.9.2 has imported some new config lines, like:

```yaml
# Computing : Eggroll, Spark, Spark_local
computing: Eggroll
# Federation: Eggroll(computing: Eggroll), Pulsar/RabbitMQ(computing: Spark/Spark_local)
federation: Eggroll
# Storage: Eggroll(computing: Eggroll), HDFS(computing: Spark), LocalFS(computing: Spark_local)
storage: Eggroll
# Algorithm: Basic, NN
algorithm: Basic
# Device: CPU, IPCL
device: CPU
```

The basic guide to update is:

```yaml
chartVersion: v1.8.0	  ->   chartVersion: v1.9.2
```

The upgrade task won't post as those new config is missing.

**Describe alternatives you've considered**

Maybe we need to clear details to update `cluster.yaml`

**Additional context**

And the 1.9.2 changed some `pod` from `deploy` to `statefull set`, the pvc created from chart has changed, the persistent data (path) need to be migrated to new path too.
